name:            squash
version:         0.0.14
description:     Minimal NodeJS browser packager
main:            lib/squash.js
license:         WTFPL
bin:
  squash:        ./bin/squash
dependencies:
  uglify-js:     1.x.x
devDependencies:
  chai:          ^2.3.0
  coffee-script: 1.x.x
  mocha:         ^2.5.3
  plantation:    0.0.16
  sinon:         ^1.17.6
  sinon-chai:    ^2.8.0
  yaml-js:       ^0.1.1
repository:
  type:          git
  url:           http://github.com/connec/squash.git
