name:            squash
version:         0.0.18
description:     Minimal NodeJS browser packager
main:            lib/squash.js
license:         WTFPL
bin:
  squash:        ./bin/squash
dependencies:
  uglify-es:     3.2.2
devDependencies:
  chai:          ^2.3.0
  coffeescript:  ^2.1.0
  mocha:         ^2.5.3
  plantation:    0.0.17
  sinon:         ^1.17.6
  sinon-chai:    ^2.8.0
  yaml-js:       ^0.2.1
repository:
  type:          git
  url:           http://github.com/connec/squash.git
